<?php
$z[0]=Array("global","\r\n            \$a=\"class='item border-box over wow fadeInUp fr'\";\r\n            \$b=\"class='item border-box over wow fadeInUp fl'\";\r\n            if ((@me%2)==0 && @me!=30) @me=\$a;\r\n            else  @me=\$b;\r\n            ",5,279);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("title","",404,418);
$z[1][4]=array();
$z[2]=Array("picname","",537,553);
$z[2][4]=array();
$z[3]=Array("title","",560,574);
$z[3][4]=array();
$z[4]=Array("picname","",776,792);
$z[4][4]=array();
$z[5]=Array("title","",799,813);
$z[5][4]=array();
$z[6]=Array("title","",965,979);
$z[6][4]=array();
$z[7]=Array("pubdate","",1034,1081);
$z[7][4]=array();
$z[7][4]['function']="MyDate('Y/m/d',@me)";
$z[8]=Array("description","",1167,1217);
$z[8][4]=array();
$z[8][4]['function']="cn_substr(@me,300)";
$z[9]=Array("arcurl","",1249,1264);
$z[9][4]=array();

?>