<?php
$z[0]=Array("global","\r\n            \$a=\"class='item wow fadeInUp fr'\";\r\n            \$b=\"class='item wow fadeInUp fl'\";\r\n            if ((@me%2)==0 && @me!=30) @me=\$a;\r\n            else  @me=\$b;\r\n            ",5,247);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("pubdate","",335,378);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y',@me)";
$z[2]=Array("pubdate","",411,456);
$z[2][4]=array();
$z[2][4]['function']="MyDate('m-d',@me)";
$z[3]=Array("arcurl","",552,567);
$z[3][4]=array();
$z[4]=Array("title","",583,597);
$z[4][4]=array();
$z[5]=Array("description","",641,691);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,500)";

?>