<?php
$z[0]=Array("field","(@me==\"\")? @me=\" class='on trans' \":@me=\"\";",535,628);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channel","\r\n        <div class=\"nav-item fl text-center trans\"><a href=\"[field:typeurl/]\">[field:typename/]</a></div>\r\n        ",655,949);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['currentstyle']="<div class='nav-item fl text-center trans'><a href='~typelink~' class='on trans'>~typename~</a></div>";

?>