<?php
$z[0]=Array("field","",238,257);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",258,284);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",325,354);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",394,452);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1496,1531);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",2527,2548);
$z[5][4]=array();
$z[5][4]['name']="content";
$z[6]=Array("type","\r\n      <div class=\"title-0 wow fadeInUp\">[field:seotitle/]</div>\r\n      <div class=\"title-1 wow fadeInUp\"><span>[field:typename/]</span></div>\r\n      ",3445,3631);
$z[6][4]=array();
$z[6][4]['typeid']="16";
$z[7]=Array("arclist","\r\n      <div class=\"item item0 fl relative text-center wow fadeInUp\">\r\n        <div class=\"img grayscale\"> <a href=\"javascript:;\" class=\"trans block\" title=\"[field:title/]\" rel=\"nofollow\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" class=\"grayscale-img max-w100 trans\"></a> </div>\r\n      </div>\r\n      ",3674,4031);
$z[7][4]=array();
$z[7][4]['typeid']="16";
$z[7][4]['row']="45";
$z[8]=Array("include","",4176,4213);
$z[8][4]=array();
$z[8][4]['filename']="footer.htm";

?>